CREATE ROLE super WITH LOGIN PASSWORD 'super';

CREATE ROLE ecommerce WITH LOGIN PASSWORD 'ecommerce' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE ecommerce_database;
GRANT ALL PRIVILEGES ON DATABASE ecommerce_database TO ecommerce;
GRANT ALL PRIVILEGES ON DATABASE ecommerce_database TO super;

